### ISSUE TITLE
Matrix room expulsion 

### ISSUE THREAD

**Issue by Zozosticot** [DanctNIX/danctnix#1]
Hello, after searching for the Matrix salon in my client, I couldn't find it. I searched for the lounge on Pine64's wiki, and when I searched for it again, it said I wasn't invited. 

Great, I didn't break any community rules (and there's no denying it, I was banned weeks after my last post, which itself was quite ordinary!) without any explanation.

Can I have some here, please?

**Comment by gamelaster** [comment]
Hi, which matrix channel?

**Comment by Zozosticot** [comment]
I'm talking about #archmobile:kde.org

**Comment by Danct12** [comment]
Try join the channel again.

**Comment by Zozosticot** [comment]
Thx !
It was a Matrix problem, no ban or departure visible in the history.
